### ISSUE TITLE
confusing log error for signature verification

### ISSUE THREAD

**Issue by meskio** [katzenpost/authority#10]
Using the authority client. If I have the wrong PKI key, so the signature validation of the consensus fails, I get this error:
```
17:02:35.502 WARN minclient/pki:bob@ramix: Failed to fetch PKI for epoch 1581: square/go-jose: error in cryptographic primitive
```

It's a bit confusing error. Will be nice if it said something about signature validation failure or something like that.

**Comment by Yawning** [comment]
Well, it's an error returned from the JOSE library that's being used (https://github.com/square/go-jose/blob/v2/shared.go#L46).  I guess I can check the error being returned and convert it to another error to fix this...
