### ISSUE TITLE
Add Voting Authority Shared Random Generation Protocol

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#20]
We  basically want to implement this protocol:
https://gitweb.torproject.org/torspec.git/tree/srv-spec.txt

which will serve as the permutation seed for randomized Topology field of the PKI Document: https://github.com/katzenpost/core/blob/master/pki/pki.go

**Comment by mixmasala** [comment]
from discussion on irc we note that tor's srv implementation keeps the same srv for 24 hours. we want to use a new srv for each epoch, so that new descriptors that are added to the consensus cannot be manipulated to predictably change a mix's position in topology.
