### ISSUE TITLE
nonvoting: Documents should contain signed descriptors on the wire.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/authority#3]
It would be nice for nodes to be able to verify their own signatures on signed descriptors, so the raw signed descriptors as received should be sent back to clients instead of the deserialized->reserialized descritpors with the signatures stripped out as is done currently.

**Comment by Yawning** [comment]
I'm not sure how much this actually matters in practice.  A malicious authority can send different documents back to each client, and sanity checking on each node is limited to validating their own descriptor.

**Comment by Yawning** [comment]
Closing this as WONTFIX.

**Comment by Yawning** [comment]
On second thought, I kind of want this to appease my tinfoil hat, and my branch shouldn't have rotted that much.

**Comment by Yawning** [comment]
The rot wasn't too bad, the only things that I really had to fix was that the topology assignment got more involved since I wrote this.  I can merge the branch whenever, but it'll require rebuilding/restarting all deployed code since the wire format of the document has changed.

**Comment by david415** [comment]
What is the format of the consensus document?

**Comment by meskio** [comment]
It looks like the providers are a base64 inside a base64. Is that intentional? Is it a bug?

**Comment by meskio** [comment]
For me it will make more sense to do something human readable like:
```
{
    "Providers": [
        {
            "Header": {"alg":"EdDSA", ...},
            "Payload": {"Version":"nonvoting-v0", ...},
            "Signature": "<base64encoded>
        },
        ... ],
     ...
}

**Comment by meskio** [comment]
I see the rfc of JWS describes the base64 encoding (so my proposal will break it :( ):
https://tools.ietf.org/html/rfc7515#page-7

But it mentions the use `.` as delimiter between the parts. I think the existing code doesn't use `.` around.

**Comment by Yawning** [comment]
Providers and Nodes are Base64 inside Base64 in Documents because of this ticket.  The raw JWS descriptors as uploaded by all the participants are included as-is in the Document, so that it is possbile to validate the descriptor signatures included in a Document.

Both the Descriptors and the Documents most certainly do use `.` correctly (and library code is used to implement JWS).
