### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#34]
unexpected fault address 0x7fa94ff9c028
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fa94ff9c028 pc=0x484728]

goroutine 10 [running]:
runtime.throw(0xd28c34, 0x5)
	/home/user/code/go1.10.3/src/runtime/panic.go:616 +0x81 fp=0xc42026fbb8 sp=0xc42026fb98 pc=0x4541e1
runtime.sigpanic()
	/home/user/code/go1.10.3/src/runtime/signal_unix.go:395 +0x211 fp=0xc42026fc08 sp=0xc42026fbb8 pc=0x46b111
runtime.memmove(0xc420426c07, 0x7fa94ff9c028, 0x1a9f)
	/home/user/code/go1.10.3/src/runtime/memmove_amd64.s:103 +0xb8 fp=0xc42026fc10 sp=0xc42026fc08 pc=0x484728
runtime.slicecopy(0xc420426c07, 0x1a9f, 0x1a9f, 0x7fa94ff9c028, 0x1a9f, 0x1a9f, 0x1, 0x32fd98f3ee2e)
	/home/user/code/go1.10.3/src/runtime/slice.go:222 +0x140 fp=0xc42026fc58 sp=0xc42026fc10 pc=0x46c970
github.com/katzenpost/core/wire/commands.(*Consensus).ToBytes(0xc420215380, 0xe9, 0x0, 0x0)
	/home/user/gopath/src/github.com/katzenpost/core/wire/commands/commands.go:214 +0x23d fp=0xc42026fce8 sp=0xc42026fc58 pc=0xb46f7d
github.com/katzenpost/core/wire.(*Session).SendCommand(0xc42035c900, 0xe20240, 0xc420215380, 0x112a560, 0x0)
	/home/user/gopath/src/github.com/katzenpost/core/wire/session.go:342 +0x8d fp=0xc42026fdd8 sp=0xc42026fce8 pc=0xbc57ed
github.com/katzenpost/authority/nonvoting/server.(*Server).onConn(0xc4200c4500, 0xe26860, 0xc4202184f8)
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/wire_handler.go:97 +0xddd fp=0xc42026ff30 sp=0xc42026fdd8 pc=0xbd078d
github.com/katzenpost/authority/nonvoting/server.(*Server).listenWorker(0xc4200c4500, 0xe23c80, 0xc42000f138)
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/server.go:150 +0x34c fp=0xc42026ffc8 sp=0xc42026ff30 pc=0xbc819c
runtime.goexit()
	/home/user/code/go1.10.3/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42026ffd0 sp=0xc42026ffc8 pc=0x483e01
created by github.com/katzenpost/authority/nonvoting/server.New
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/server.go:267 +0xbdd

goroutine 1 [chan receive]:
github.com/katzenpost/authority/nonvoting/server.(*Server).Wait(...)
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/server.go:123
main.main()
	/home/user/gopath/src/github.com/katzenpost/daemons/authority/nonvoting/main.go:75 +0x4a6

goroutine 5 [syscall]:
os/signal.signal_recv(0x483e01)
	/home/user/code/go1.10.3/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/home/user/code/go1.10.3/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.0
	/home/user/code/go1.10.3/src/os/signal/signal_unix.go:28 +0x4f

goroutine 7 [select, locked to thread]:
runtime.gopark(0xd4adb8, 0x0, 0xd29df8, 0x6, 0x18, 0x1)
	/home/user/code/go1.10.3/src/runtime/proc.go:291 +0xf9
runtime.selectgo(0xc42004ef50, 0xc42007e300)
	/home/user/code/go1.10.3/src/runtime/select.go:392 +0x11d4
runtime.ensureSigM.func1()
	/home/user/code/go1.10.3/src/runtime/signal_unix.go:549 +0x19f
runtime.goexit()
	/home/user/code/go1.10.3/src/runtime/asm_amd64.s:2361 +0x1

goroutine 8 [chan receive]:
github.com/katzenpost/authority/nonvoting/server.New.func2(0xc4200c4500)
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/server.go:245 +0x65
created by github.com/katzenpost/authority/nonvoting/server.New
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/server.go:244 +0x742

goroutine 9 [select]:
github.com/katzenpost/authority/nonvoting/server.(*state).worker(0xc42018c3f0)
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/state.go:105 +0x1bc
github.com/katzenpost/authority/nonvoting/server.(*state).(github.com/katzenpost/authority/nonvoting/server.worker)-fm()
	/home/user/gopath/src/github.com/katzenpost/authority/nonvoting/server/state.go:630 +0x42
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc42018c408, 0xc4201cd7f0)
	/home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:38 +0x5d
created by github.com/katzenpost/core/worker.(*Worker).Go
	/home/user/gopath/src/github.com/katzenpost/core/worker/worker.go:36 +0xc5

goroutine 11 [chan receive]:
main.main.func1(0xc42007e240, 0xc4200c4500)
	/home/user/gopath/src/github.com/katzenpost/daemons/authority/nonvoting/main.go:64 +0x42
created by main.main
	/home/user/gopath/src/github.com/katzenpost/daemons/authority/nonvoting/main.go:63 +0x44d

goroutine 12 [chan receive]:
main.main.func2(0xc42007e3c0, 0xc4200c4500)
	/home/user/gopath/src/github.com/katzenpost/daemons/authority/nonvoting/main.go:70 +0x42
created by main.main
	/home/user/gopath/src/github.com/katzenpost/daemons/authority/nonvoting/main.go:69 +0x479

**Comment by mixmasala** [comment]
Any idea how to recreate this and/or what release/branch this is from? Concurrency issue? Was the consensus payload nil?

**Comment by mixmasala** [comment]
@david415 any way to reproduce this issue?
