### ISSUE TITLE
fix pki document Topology

### ISSUE THREAD

**Issue by david415** [Katzenpost/authority#5]
according to a client error in the integration test, the PKI has a bug related to the Topology field of the published documents:

```
22:41:02.288 DEBU Sender-alice@provider-0.example.org: Failed to compose Sphinx packet: RouteFactory.Build failed: pki: invalid layer: '3'
```

**Comment by Yawning** [comment]
This is a sanity check in the `core/pki` helper failing, but I'm not sure it's a bug in either the authority or core helpers.  A well formed document won't have a layer `3`, because it's 0 indexed.

```
func (d *Document) GetMixesInLayer(layer uint8) ([]*MixDescriptor, error) {
        if len(d.Topology)-1 < int(layer) {
                return nil, fmt.Errorf("pki: invalid layer: '%v'", layer)
        }
        return d.Topology[layer], nil
}
```

**Comment by david415** [comment]
ah i know. it's a bug i recently introduced into the client because i was confused by the meaning of NrHops:
https://github.com/Katzenpost/core/blob/master/sphinx/constants/constants.go#L32

i should be able to easily fix this.

**Comment by david415** [comment]
fixed in client
