### ISSUE TITLE
MUST expose link public key

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#50]
the voting authority operator has no way to get their link key without writing code. this makes me sad... i am going to fix this. also on a related note: link keys are derived from identity keys. this buys us nothing. let's just generate link keys separately.

**Comment by mixmasala** [comment]
I think it might make sense to figure out how to use the certificate module here and sign the link keys with the identity keys. Currently authority configuration - the identity and link keys of the peers is stored in .toml and present on all nodes (clients, mixes, other authorities). Key rotation implies updating a bunch of .toml files on every node. If we can sign link keys with the identity (or signing) key we don't need to publish the link keys in .toml files everywhere and can rotate them more easily.

**Comment by david415** [comment]
i think you are confused. the purpose of this ticket is to fix a bug. i have done so here: https://github.com/katzenpost/authority/pull/51
