### ISSUE TITLE
conflated authorization + conflated state machines

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#54]
tl,dr; highly critical security/anonymity bug that needs to be fixed.

Both the nonvoting and the voting directory authorities have a bug. For the nonvoting authority it is much less severe.

1. nonvoting

The authentication mechanism for incoming connections is broken AND the server statemachine does NOT distinguish between the two client peer types which are mix and non-mix clients.

2. voting

Same as above but there is also a third class of client peer which are the Directory Authority peers.

There are various implications for the voting authority one of which is: anyone can cause the SRV protocol to fail or influence it's result. The influence over the result is the scary part because the SRV protocol is used to set the topology.

**Comment by mixmasala** [comment]
I believe this has been fixed in https://github.com/katzenpost/authority/pull/58 and https://github.com/katzenpost/authority/pull/57
