### ISSUE TITLE
increase duration of bootstrap phase

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#61]
during deployment of a test mixnet i noticed that the voting authorities would fail to reach consensus during "mixnet bootup" if i wait too long to start the mixes and providers after starting the authority servers. i would argue that the bootstrap duration is too short and that this is a bug.

**Comment by mixmasala** [comment]
it's true that 30s is an "ass number". It's fine for automated testing, and breaks for deploying real mixnets. I think we should turn off bootstrapping for real mixnets. Is it a problem to wait a few hours?

**Comment by mixmasala** [comment]
I've removed the bootstrap path (https://github.com/katzenpost/authority/pull/71) because it creates a lot of complexity.
