### ISSUE TITLE
more verbose error messages

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#66]
```
21:07 < dawuud> 21:06:49.648 DEBU state: Current epoch 4607
21:07 < dawuud> 21:06:49.648 DEBU state: Combining signatures for epoch 4607
21:07 < dawuud> 21:06:49.650 ERRO state: No consensus found for epoch 4607
```

it is not possible to understand from the error messages why it is that consensus failed.

**Comment by mixmasala** [comment]
There are likely plenty of preceding DEBUG level messages that give a clue as to why this failed, and likely it is that there aren't enough signatures to make a consensus. Please include the complete logfiles and a brief description of the test setup.
