### ISSUE TITLE
add version numbers to Document and MixDescriptor

### ISSUE THREAD

**Issue by david415** [katzenpost/authority#9]
shouldn't we version all of the things?

**Comment by Yawning** [comment]
https://github.com/katzenpost/authority/blob/master/nonvoting/internal/s11n/descriptor.go#L40

https://github.com/katzenpost/authority/blob/master/nonvoting/internal/s11n/document.go#L35

**Comment by Yawning** [comment]
https://github.com/katzenpost/authority/blob/master/nonvoting/internal/s11n/descriptor.go#L40

https://github.com/katzenpost/authority/blob/master/nonvoting/internal/s11n/document.go#L35
