### ISSUE TITLE
Invalid GenesisEpoch checking causes panic

### ISSUE THREAD

**Issue by sebohe** [katzenpost/authority#96]
With the recent [katzenpost/authority](https://github.com/katzenpost/authority/tree/v0.0.12) release v0.0.12 a new check for GenesisEpoch for the consensus document got added:

https://github.com/katzenpost/authority/blob/master/internal/s11n/document.go#L181

In [Meson](https://github.com/hashcloak/Meson-client/blob/master/client.go#L96)  we are using the katzenpost/client code to test the cryptocurrency CBOR plugin. And we use the `AutoRegisterRandomClient` function that registers a new __Non voting__ pki client:

New pkiClient: https://github.com/katzenpost/client/blob/master/client.go#L53.

That calls `pkiClient.Get()`: https://github.com/katzenpost/client/blob/master/client.go#L60

`.Get()` calls `s11n.VerifyAndParseDocument()`: https://github.com/katzenpost/authority/blob/master/nonvoting/client/client.go#L175

Which generates a new document struct that has GenesisEpoch defaulted to `0`: https://github.com/katzenpost/authority/blob/8ea0d9d399042922832002ab522a93b6784b3dcd/internal/s11n/document.go#L145

Error that gets raised in our client code:
```
11:18:18.109 NOTI katzenpost/client: 😼 Katzenpost is still pre-alpha.  DO NOT DEPEND ON IT FOR STRONG SECURITY OR ANONYMITY. 😼
11:18:18.109 DEBU pki/nonvoting/client: Get(ctx, 781509)
panic: Document has invalid GenesisEpoch

goroutine 1 [running]:
github.com/katzenpost/client.AutoRegisterRandomClient(0xc000553270, 0x0, 0x0)
        /home/sebas/repos/hashcloack/katzenpost/client/client.go:66 +0xab2
github.com/hashcloak/Meson-client.(*Client).Start(0xc0000ade00, 0x1e, 0xc000131230)
        /home/sebas/repos/hashcloack/Meson-client/client.go:39 +0x33
main.main()
        /home/sebas/repos/hashcloack/Meson-client/integration/tests.go:163 +0x324
exit status 2
```

I looked at the [voting](https://github.com/katzenpost/authority/blob/master/voting/client/client.go#L296) version of the client to see if there is any difference but the `.Get` function does not vary much. It only checks that there is a majority voting consensus on the epoch document.

`VerifyAndParseDocument` decodes the `r.Payload` argument passed to it. It assigns the result of the decode to `d` a few lines after `d := new(Document)`. I tried looking into what `r.Payload` is and see if adding a `GenesisEpoch` field to the struct it returns: https://github.com/katzenpost/core/blob/master/wire/commands/commands.go#L169. This seemed like it would cause too much impact on several other parts of the code base.

I don't know enough to know how to initialize a value for `d.GenesisEpoch`, but I think it needs to or else the `d.GenesisEpoch == 0` check will always raise an error.

**Comment by mixmasala** [comment]
Just updating here as well as from IRC, I suspect the problem is that the running nonvoting authority is older than the client lib used.
If you have debug logging enabled for your nonvoting authority, check to see if the 'GenesisEpoch' is set in the consensus document (grep for GenesisEpoch).

I guess we should think hard about how to properly support version mismatches between authority/client instances.

Thanks for reporting this issue - let me know if that is indeed the case.

**Comment by sebohe** [comment]
So I began looking for GenesisEpoch in the log file and indeed it is missing. Something was wrong in my build process so it wasn't using the latest authority. When I did use the latest authority everything is working fine.
Thanks for your time!
